### PR TITLE
feat: support INIT_CWD env

### PR DESCRIPTION
**Pull request by fengmk2**
closes https://github.com/cnpm/cnpm/issues/317

### CODE REVIEW

**Comment by fengmk2** [comment]
from https://github.com/cnpm/npminstall/pull/321

**Comment by fengmk2** [comment]
3.26.0

**Comment by HeavenSky** [comment]
I found this issue isn't fixed in both 3.26.0 and 4.6.0 .
@fengmk2 

image

**Comment by fengmk2** [comment]
@HeavenSky you should create a package.json file and set `name` property.

**Comment by afc163** [comment]
cnpm 什么时候能修复？

**Comment by fengmk2** [comment]
@afc163 重新安装 cnpm 就获得这个能力了。

**Pull request merged**
