### PR TITLE
fix: ensure read and write permission like npm

### PR DESCRIPTION
**Pull request by dead-horse**
This change is [Reviewable](https://reviewable.io/reviews/cnpm/npminstall/245)

### CODE REVIEW

**Comment by fengmk2** [comment]
奇葩。。。

image

**Comment by fengmk2** [comment]
windows 挂了

image

**Comment by dead-horse** [comment]
看来 windows 是 666，我在 windows 下跳过这个测试好了，没什么意义

**Comment by fengmk2** [comment]
3.1.2

**Pull request merged**
