### PR TITLE
fix: store path starts with `_{name}`

### PR DESCRIPTION
**Pull request by fengmk2**
fixes https://github.com/cnpm/npminstall/pull/220

---
This change is [Reviewable](https://reviewable.io/reviews/cnpm/npminstall/223)

### CODE REVIEW

**Comment by fengmk2** [comment]
It cause some bug on css-loader 
image

**Comment by dead-horse** [comment]
等 CI

**Comment by fengmk2** [comment]
可以合并发布 了

**Comment by dead-horse** [comment]
2.29.1

**Pull request merged**
